#!/usr/bin/env bash
# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
# ~/.yabairc

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# ====== Variables =============================

gaps_top="30"
gaps_bottom="10"
gaps_left="10"
gaps_right="10"
gaps_inner="10"


# ====== Tiling settings =======================

# 使用 font-awesome 替代罗马数字

yabai -m config status_bar_position bottom

#yabai -m config layout                      stack
yabai -m config layout                      bsp
#yabai -m config layout                         float

# bar settings

yabai -m config top_padding                 "${gaps_top}"
yabai -m config bottom_padding              "${gaps_bottom}"
yabai -m config left_padding                "${gaps_left}"
yabai -m config right_padding               "${gaps_right}"
yabai -m config window_gap                  "${gaps_inner}"

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

yabai -m config window_shadow               float


yabai -m config split_ratio                 0.5
yabai -m config auto_balance                off

#设置焦点跟随鼠标模式（默认：关闭，选项：关闭，自动提升，自动聚焦）
yabai -m config focus_follows_mouse			autofocus
#鼠标跟随聚焦窗口
yabai -m config mouse_follows_focus			on

#设置浮动窗口停留在顶部
yabai -m config window_topmost				off

#透明度
yabai -m config window_opacity              on
#聚焦窗口的不透明度
yabai -m config active_window_opacity       1.0
#不聚焦窗口的不透明度
yabai -m config normal_window_opacity       0.9


# ====== Border settings =======================

yabai -m config window_border  off
yabai -m config window_border_width         1
yabai -m config active_window_border_color  0xcc00008b


# ====== List of rules =========================

# yabai -m rule --add label=chrome app="^Google Chrome$" space=2

#yabai -m rule --add label=kitty app="^kitty$" space=1

# yabai -m rule --add label=wechat app="^ 微信 $" space=10
# yabai -m rule --add label=qq app="^ 微信" space=10


yabai -m rule --add label=Google Chrome app="^Google Chrome$" space=2

# yabai -m rule --add label=androidstudio app="^Android Studio$" space=3

yabai -m rule --add label=musicapp app="^Music$" space=10
yabai -m rule --add label=musicapp app="QQ音乐" space=10

# yabai -m rule --add label=iina app="^IINA$" space=5

# yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off border=off


# 临时性的App 也就是manage=off不受到yabai平铺式的限制，之前怎么弹出来就怎么弹出来
otherApp='^(IINA|访达|Calendar|日历|System Preferences|系统偏好设置|企业微信|预览|Mail|微信|WeChatc|QQ|QQ音乐|Android Studio|印象笔记|归档实用工具|Übersicht|OpenCore Configurator|iStat Menus Status)$'
yabai -m rule --add app="${otherApp}" manage=off

yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"

